# Generated by Django 5.2 on 2025-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_type',
            field=models.CharField(choices=[('solar', '양력'), ('lunar', '음력')], default='solar', max_length=10, verbose_name='양력/음력'),
        ),
    ]
