# Generated by Django 5.2.6 on 2025-11-27 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=7, unique=True, verbose_name='색상 코드 (HEX)')),
                ('color_name', models.CharField(max_length=50, verbose_name='색상 이름')),
                ('color_category', models.CharField(blank=True, max_length=30, verbose_name='색상 카테고리')),
                ('rgb_r', models.IntegerField(verbose_name='Red')),
                ('rgb_g', models.IntegerField(verbose_name='Green')),
                ('rgb_b', models.IntegerField(verbose_name='Blue')),
                ('hsl_h', models.IntegerField(blank=True, null=True, verbose_name='Hue')),
                ('hsl_s', models.IntegerField(blank=True, null=True, verbose_name='Saturation')),
                ('hsl_l', models.IntegerField(blank=True, null=True, verbose_name='Lightness')),
                ('meaning', models.TextField(blank=True, verbose_name='색상의 의미')),
                ('fortune_keywords', models.JSONField(default=list, verbose_name='운세 관련 키워드')),
            ],
            options={
                'verbose_name': '색상 마스터',
                'verbose_name_plural': '색상 마스터',
                'db_table': 'color_master',
            },
        ),
        migrations.CreateModel(
            name='DailyFortuneCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, verbose_name='세션 키 (비회원용)')),
                ('fortune_date', models.DateField(db_index=True, verbose_name='운세 날짜')),
                ('fortune_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='운세 점수')),
                ('fortune_text', models.TextField(verbose_name='운세 내용')),
                ('lucky_color', models.CharField(max_length=7, verbose_name='대표 행운색 (HEX)')),
                ('lucky_colors_json', models.TextField(default='[]', verbose_name='행운색 목록 (JSON)')),
                ('lucky_number', models.IntegerField(blank=True, null=True, verbose_name='행운의 숫자')),
                ('lucky_direction', models.CharField(blank=True, max_length=20, verbose_name='행운의 방향')),
                ('zodiac_sign', models.CharField(blank=True, max_length=20, verbose_name='별자리')),
                ('chinese_zodiac', models.CharField(blank=True, max_length=20, verbose_name='띠')),
                ('saju_data', models.TextField(blank=True, default='{}', verbose_name='사주 데이터 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '일일 운세 캐시',
                'verbose_name_plural': '일일 운세 캐시',
                'db_table': 'daily_fortune_cache',
            },
        ),
        migrations.CreateModel(
            name='FortuneBaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('heavenly_stem', '천간'), ('earthly_branch', '지지'), ('five_elements', '오행'), ('zodiac', '별자리'), ('chinese_zodiac', '띠')], max_length=50, verbose_name='카테고리')),
                ('code', models.CharField(max_length=20, verbose_name='코드')),
                ('name_ko', models.CharField(max_length=50, verbose_name='한국어 이름')),
                ('name_cn', models.CharField(blank=True, max_length=50, verbose_name='한자')),
                ('attributes', models.JSONField(default=dict, verbose_name='속성')),
                ('compatibility', models.JSONField(default=dict, verbose_name='상성/상극 정보')),
            ],
            options={
                'verbose_name': '운세 기본 데이터',
                'verbose_name_plural': '운세 기본 데이터',
                'db_table': 'fortune_base_data',
            },
        ),
        migrations.CreateModel(
            name='MBTISpeechTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=4, verbose_name='MBTI 유형')),
                ('category', models.CharField(choices=[('greeting', '인사말'), ('fortune_good', '좋은 운세'), ('fortune_bad', '나쁜 운세'), ('recommendation', '추천'), ('encouragement', '격려'), ('advice', '조언')], max_length=50, verbose_name='카테고리')),
                ('template_text', models.TextField(verbose_name='템플릿 텍스트')),
                ('tone', models.CharField(choices=[('formal', '격식체'), ('casual', '편안한'), ('friendly', '친근한')], default='friendly', max_length=20, verbose_name='어조')),
            ],
            options={
                'verbose_name': 'MBTI 말투 템플릿',
                'verbose_name_plural': 'MBTI 말투 템플릿',
                'db_table': 'mbti_speech_templates',
            },
        ),
    ]
