# Generated by Django 5.2.6 on 2025-11-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fortune', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfortunecache',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='fortunebasedata',
            unique_together={('category', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='mbtispeechtemplate',
            unique_together={('mbti_type', 'category')},
        ),
        migrations.AddIndex(
            model_name='dailyfortunecache',
            index=models.Index(fields=['fortune_date', '-created_at'], name='daily_fortu_fortune_f54d25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfortunecache',
            unique_together={('session_key', 'fortune_date'), ('user', 'fortune_date')},
        ),
    ]
