# Generated by Django 5.2.6 on 2025-12-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfortunecache',
            name='full_fortune_data',
            field=models.TextField(blank=True, default='{}', verbose_name='전체 운세 데이터 (JSON)'),
        ),
    ]
