# Generated by Django 5.2.6 on 2025-12-03 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_dailyfortunecache_full_fortune_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfortunecache',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='dailyfortunecache',
            name='birth_time',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='태어난 시간'),
        ),
        migrations.AddField(
            model_name='dailyfortunecache',
            name='calendar_type',
            field=models.CharField(blank=True, default='solar', max_length=10, verbose_name='양력/음력'),
        ),
        migrations.AddField(
            model_name='dailyfortunecache',
            name='chinese_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='한자 이름'),
        ),
        migrations.AddIndex(
            model_name='dailyfortunecache',
            index=models.Index(fields=['fortune_date', 'birth_date', 'birth_time', 'chinese_name'], name='daily_fortu_fortune_7789f2_idx'),
        ),
    ]
