# Generated by Django 5.2.6 on 2025-12-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0005_weeklyfortunecache_monthlyfortunecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfortunecache',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='weeklyfortunecache',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='성별'),
        ),
    ]
