# Generated by Django 5.2.6 on 2025-11-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='아이템 이름')),
                ('item_category', models.CharField(blank=True, choices=[('top', '상의'), ('bottom', '하의'), ('outer', '아우터'), ('dress', '원피스'), ('shoes', '신발'), ('bag', '가방'), ('accessory', '악세서리'), ('etc', '기타')], max_length=50, null=True, verbose_name='카테고리')),
                ('main_category', models.CharField(blank=True, choices=[('clothing', '의류'), ('cosmetics', '화장품'), ('electronics', '전자제품'), ('accessories', '악세서리'), ('etc', '기타')], max_length=50, null=True, verbose_name='대분류')),
                ('sub_categories', models.JSONField(default=list, help_text='소분류 목록 또는 기타 카테고리의 경우 사용자 입력값', verbose_name='소분류 (목록)')),
                ('image', models.ImageField(upload_to='items/%Y/%m/', verbose_name='이미지')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('dominant_colors', models.JSONField(default=list, verbose_name='주요 색상들')),
                ('ai_analysis_result', models.JSONField(default=dict, verbose_name='AI 분석 결과')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='즐겨찾기')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사용자 아이템',
                'verbose_name_plural': '사용자 아이템',
                'db_table': 'user_items',
            },
        ),
    ]
