# Generated by Django 5.2.6 on 2025-11-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='useritem',
            index=models.Index(fields=['user', 'item_category'], name='user_items_user_id_41e309_idx'),
        ),
        migrations.AddIndex(
            model_name='useritem',
            index=models.Index(fields=['user', 'main_category'], name='user_items_user_id_1fc13f_idx'),
        ),
        migrations.AddIndex(
            model_name='useritem',
            index=models.Index(fields=['user', 'is_favorite'], name='user_items_user_id_22760f_idx'),
        ),
    ]
