# Generated by Django 5.2.6 on 2025-12-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='image_url',
        ),
    ]
