# Generated by Django 5.2.6 on 2025-11-27 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, verbose_name='세션 키')),
                ('recommendation_date', models.DateField(db_index=True, verbose_name='추천 날짜')),
                ('recommendation_type', models.CharField(choices=[('OOTD', 'OOTD'), ('MENU', '메뉴'), ('ITEM', '아이템'), ('ACTIVITY', '활동')], max_length=10, verbose_name='추천 타입')),
                ('recommendation_data', models.JSONField(verbose_name='추천 상세 데이터')),
                ('weather_data', models.JSONField(default=dict, verbose_name='날씨 정보')),
                ('user_feedback', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='사용자 평점')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '일일 추천',
                'verbose_name_plural': '일일 추천',
                'db_table': 'daily_recommendations',
            },
        ),
        migrations.CreateModel(
            name='MenuRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200, verbose_name='메뉴 이름')),
                ('menu_category', models.CharField(choices=[('korean', '한식'), ('chinese', '중식'), ('japanese', '일식'), ('western', '양식'), ('asian', '아시안'), ('snack', '분식'), ('cafe', '카페'), ('etc', '기타')], max_length=50, verbose_name='메뉴 카테고리')),
                ('menu_color_match', models.JSONField(default=dict, verbose_name='색상 매칭 정보')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='칼로리')),
                ('recipe_link', models.URLField(blank=True, verbose_name='레시피 링크')),
                ('restaurant_suggestion', models.CharField(blank=True, max_length=200, verbose_name='추천 식당')),
            ],
            options={
                'verbose_name': '메뉴 추천',
                'verbose_name_plural': '메뉴 추천',
                'db_table': 'menu_recommendations',
            },
        ),
        migrations.CreateModel(
            name='OOTDRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_color', models.CharField(max_length=7, verbose_name='상의 색상')),
                ('bottom_color', models.CharField(max_length=7, verbose_name='하의 색상')),
                ('outer_required', models.BooleanField(default=False, verbose_name='아우터 필요')),
                ('outer_color', models.CharField(blank=True, max_length=7, verbose_name='아우터 색상')),
                ('sleeve_type', models.CharField(choices=[('SHORT', '반팔'), ('LONG', '긴팔'), ('SLEEVELESS', '민소매')], max_length=10, verbose_name='소매 타입')),
                ('style_tags', models.JSONField(default=list, verbose_name='스타일 태그')),
                ('matching_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='매칭 점수')),
            ],
            options={
                'verbose_name': 'OOTD 추천',
                'verbose_name_plural': 'OOTD 추천',
                'db_table': 'ootd_recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('color', '색상'), ('style', '스타일'), ('food', '음식'), ('activity', '활동')], max_length=50, verbose_name='선호도 타입')),
                ('preference_value', models.CharField(max_length=200, verbose_name='선호 값')),
                ('score', models.FloatField(default=0, verbose_name='선호도 점수')),
                ('interaction_count', models.IntegerField(default=0, verbose_name='상호작용 횟수')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트')),
            ],
            options={
                'verbose_name': '사용자 선호도',
                'verbose_name_plural': '사용자 선호도',
                'db_table': 'user_preferences',
            },
        ),
    ]
