# Generated by Django 5.2.6 on 2025-11-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='menurecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_details', to='recommendations.dailyrecommendation', verbose_name='추천'),
        ),
        migrations.AddField(
            model_name='ootdrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ootd_details', to='recommendations.dailyrecommendation', verbose_name='추천'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='dailyrecommendation',
            index=models.Index(fields=['recommendation_date', 'user'], name='daily_recom_recomme_002ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecommendation',
            index=models.Index(fields=['recommendation_date', 'session_key'], name='daily_recom_recomme_010f30_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user', 'preference_type'], name='user_prefer_user_id_98103b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'preference_type', 'preference_value')},
        ),
    ]
